### PR TITLE
Make maps and list use same api call

### LINKED ISSUE #8: Maps vs List
Both should now be switched to using the same API call and data so that locations.json isn't called twice. Should include the `type` filter as a parameter (as currently done by map) and `lat,lng` (as currently done by list).

### PR DESCRIPTION
**Pull request by dbalatero**
@ezwelty This closes #8.

However, I wanted to get your input on something… by changing both API calls to include `lat,lng` center coordinates, this had the effect of really tightly clustering all the locations towards the center of the map. Does this seem bad to you?

*current master version*
screenshot 2017-03-04 22 31 52

*this new branch*
screenshot 2017-03-04 22 31 24

### CODE REVIEW

**Comment by ezwelty** [comment]
@dbalatero Yeah, I knew this was coming. On the one hand, it makes it impossible for the user to gauge the overall point coverage; on the other, it makes the list load faster, it's more representative of the true point density, and it keeps the distance-sorted list and the map in sync.

On the [website](https://fallingfruit.org/), at low zoom levels, we communicate coverage by using pre-computed clusters, and further in, by a message (which may be broken as it doesn't currently display) of "Showing X of Y points" to indicate that point density is greater than shown. I wonder if, for the mobile app, if we stick to points nearest the map center, we could use a message like "Only showing the X nearest points" or some sort of overlay that communicates the search coverage of the current map (like in video games where the map your character has explored is lit up, and the rest is shrouded in mysterious darkness).

**Comment by dbalatero** [comment]
@ezwelty Could we bump the number of points we show?

**Comment by ezwelty** [comment]
@dbalatero Hmm, the number of points needed to fill the map is depended on how far you're zoomed out, but at default zoom level 14 over Boulder, that'd be 5000+ points. I expect that would wreck performance and make our server cry.

**Comment by dbalatero** [comment]
@ezwelty one thing I've seen before is showing bubbles with larger counts in them, that you can zoom into and uncover? dunno your thoughts on clustering like that…

**Comment by ezwelty** [comment]
> On the [website](fallingfruit.org), at low zoom levels, we communicate coverage by using pre-computed clusters, and further in, by a message (which may be broken as it doesn't currently display) of "Showing X of Y points" to indicate that point density is greater than shown. I wonder if, for the mobile app, if we stick to points nearest the map center, we could use a message like "Only showing the X nearest points" or some sort of overlay that communicates the search coverage of the current map (like in video games where the map your character has explored is lit up, and the rest is shrouded in mysterious darkness).

Please see our [website](fallingfruit.org) ;)

**Pull request merged**
